language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - chmod +x ./scripts/build.sh && ./scripts/build.sh

deploy:
  skip_cleanup: true
  provider: script
  github-token: $GH_TOKEN
  on:
    branch: master

after_deploy:
  - git config user.name "${GITHUB_NAME}"
  - git config user.email "${GITHUB_EMAIL}"
  - git remote add gh-token "https://${GH_TOKEN}@github.com/${GITHUB_NAME}/CSU_CS_Experiment.git";
  - mkdocs gh-deploy -v --clean --remote-name gh-token;