language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc

script:
  - chmod +x ./scripts/build.sh && ./scripts/build.sh
  - mkdocs gh-deploy --force --clean
