site_name: CSU CS wiki
site_description: CSU CS wiki
site_author: 妄想
site_url: https://leo6033.github.io/CSU_CS_Experiment/
strict: true

# Repository
repo_name: "leo6033/CSU_CS_Experiment"
repo_url: "https://github.com/leo6033/CSU_CS_Experiment"
edit_uri: "https://leo6033.github.io/CSU_CS_Experiment/edit-landing/?ref="

# Contents
nav:
  - 简介:
      - Getting Started: index.md
      - 如何参与: intro/htc.md
  - 数字图像处理:
      - 理想滤波器与振铃特性: imageprocess/ilpf.md
  - 软件测试:
      - 白盒测试开发: softwaretesting/white-box.md
      - 黑盒测试开发: softwaretesting/black-box.md
      - TDD测试驱动开发: softwaretesting/tdd.md
  - 编译原理:
      - 算符优先文法: compilerprincipal/opg.md
  - 分布式系统与云计算:
      - 时间同步算法: distributedsystems/sync-clock.md
      - Lamport逻辑时钟: distributedsystems/logic-clock.md
      - 期末汇总（临时）: distributedsystems/sumup.md
  - 竞赛:
      - 关于竞赛:  competition/index.md

# Theme
theme:
  name: material
  custom_dir: "mkdocs-material/material"
  static_templates:
    - 404.html
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  include_search_page: false
  search_index_only: true
  favicon: "favicon.png"

  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"

# Customization
extra:
  search:
    language: "jp"
  disqus: "CSU CS Wiki"
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: "on"
  githash: "2ac34dc"
#   palette:
#     primary: 'Blue Grey'
#     accent: 'Pink'

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  - "_static/js/extra.js"

extra_css:
  - "_static/css/extra.css"
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
