site_name: CSU CS Wiki
site_description: CSU CS Wiki
site_author: Disc0ver
site_url: https://disc0ver-csu.github.io/csu-cs-wiki
strict: true

# Repository
repo_name: "disc0ver-csu/csu-cs-wiki"
repo_url: "https://github.com/disc0ver-csu/csu-cs-wiki"
edit_uri: "https://disc0ver-csu.github.io/csu-cs-wiki/edit-landing/?ref="

# Contents
nav:
  - 简介:
      - 关于我们: index.md
      - Quick Start: Intro/quick-start.md
      - 贡献Wiki词条标准: Intro/docs-guide.md
      - 贡献代码标准: Intro/codes-guide.md
      - Commit 标准: Intro/commit-guide.md
  - 操作系统:
      - 进程管理: OperatingSystems/process-mgmt.md
  - 分布式系统与云计算:
      - 时间同步算法: DistributedSystems/sync-clock.md
      - Lamport逻辑时钟: DistributedSystems/logic-clock.md
      - 期末汇总（临时）: DistributedSystems/sumup.md
  - 离散数学:
      - 离散数学概论: DiscreteMathematics/intro.md
      - 逻辑与证明——概论: DiscreteMathematics/logic-proof-intro.md
      - 逻辑与证明——命题与逻辑等价: DiscreteMathematics/logic-proof-prop.md
      - 逻辑与证明——谓词与量词: DiscreteMathematics/logic-proof-pred.md
      - 逻辑与证明——推理证明方法: DiscreteMathematics/logic-proof-proof.md
      - 集合论——集合: DiscreteMathematics/set-theory-sets.md
      - 集合论——关系及其性质: DiscreteMathematics/set-theory-relations-properties.md
      - 集合论——序关系与等价关系: DiscreteMathematics/set-theory-order-equivalence.md
      - 集合论——函数: DiscreteMathematics/set-theory-functions.md
      - 图论: DiscreteMathematics/graphs.md
  - 编译原理:
      - 语言与语法描述: CompilerPrinciples/language-grammar.md
      - 词法分析——有限自动机: CompilerPrinciples/lexer-dfa.md
      - 词法分析——转换算法: CompilerPrinciples/lexer-trans-algorithm.md
      - 语法分析——算符优先: CompilerPrinciples/parser-opg.md
      - 语法分析——LR分析法: CompilerPrinciples/parser-lr.md

  - 数字图像处理:
      - 理想滤波器与振铃特性: DigitalImageProcess/ilpf.md
  - 软件测试:
      - 白盒测试开发: SoftwareTesting/white-box.md
      - 黑盒测试开发: SoftwareTesting/black-box.md
      - TDD测试驱动开发: SoftwareTesting/tdd.md

  - 竞赛:
      - 关于竞赛: Competition/index.md
  - 项目招新:
      - 关于: JoinUs/index.md
      - 本项目: JoinUs/disc0ver.md
      - 开源项目: JoinUs/opensource-project.md
      - 个人项目: JoinUs/personal-project.md
      - 校内项目: JoinUs/campus-project.md

# Theme
theme:
  name: material
  custom_dir: "mkdocs-material/material"
  static_templates:
    - 404.html
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  include_search_page: false
  search_index_only: true
  favicon: "Disc0ver-blue.png"

  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"

# Customization
extra:
  search:
    language: "jp"
  disqus: "CSU CS Wiki"
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: "on"
  githash: "2ac34dc"
#   palette:
#     primary: 'Blue Grey'
#     accent: 'Pink'

extra_javascript:
  # cloudflare的mathjax cdn挂了
  # - "https://cdn.js.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
  # 新的 mathjax链接
  - "https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  # katex
  # - "https://cdn.staticfile.org/KaTeX/0.11.1/"
  - "_static/js/extra.js"

extra_css:
  - "_static/css/extra.css"
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
